name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  node14:
    name: Node 14
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: checkout node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run cs
      - run: npm test -- --coverage --no-cache
      - run: npm run infection
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
  node16:
    name: Node 16
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: checkout node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run cs
      - run: npm test -- --coverage --no-cache
      - run: npm run infection
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
  node18:
    name: Node 18
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: checkout node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: npm install
      - run: npm run cs
      - run: npm test -- --coverage --no-cache
      - run: npm run infection
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
      - name: coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: sonarcloud.io
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
